name: auto-pr

on:
  push:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'ci/**'
      - 'chore/**'
      - 'docs/**'
      - 'refactor/**'
      - 'build/**'
      - 'test/**'

permissions:
  contents: read

jobs:
  create-pr:
    uses: guilhermelinosp/templates/.github/workflows/auto-pr.yml@f1f6b00418bcdce7fb2357b12211f0dfb61783cc # templates PR #152
    with:
      app-client-id: ${{ vars.HELLNET_ACTIONS_CLIENT_ID }}
    secrets: inherit
