name: auto-pr

on:
  push:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'ci/**'
      - 'chore/**'
      - 'docs/**'
      - 'refactor/**'
      - 'build/**'
      - 'test/**'

permissions:
  contents: read

jobs:
  create-pr:
    uses: guilhermelinosp/templates/.github/workflows/auto-pr.yml@9aa4a279f308556891c0e24ae61d26c33e36ed3e # templates PR #152
    with:
      app-client-id: ${{ vars.HELLNET_ACTIONS_CLIENT_ID }}
    secrets: inherit
