name: pr-check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  merge-check:
    uses: guilhermelinosp/templates/.github/workflows/merge-check.yml@e7d093b460c1e25f16121d509eefcbb597612c95 # main

  gitleaks:
    uses: guilhermelinosp/templates/.github/workflows/gitleaks.yml@e7d093b460c1e25f16121d509eefcbb597612c95 # main

  labeler:
    uses: guilhermelinosp/templates/.github/workflows/labeler.yml@9aa28e4932048b724e165f169963643e8c4bcd69 # main

