name: release

on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.release.outputs.version }}

jobs:
  release:
    uses: guilhermelinosp/templates/.github/workflows/release.yml@8f299961846cf1d0cbf7129a99ea6c3095ec3abd
    with:
      app-client-id: ${{ vars.HELLNET_ACTIONS_CLIENT_ID }}
    secrets: inherit
