name: release

on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.release.outputs.version }}

jobs:
  release:
    uses: guilhermelinosp/templates/.github/workflows/release.yml@41fa69bdb033100b4386fd993d9cf3aff0be1c4f # templates PR #152
    with:
      app-client-id: ${{ vars.HELLNET_ACTIONS_CLIENT_ID }}
    secrets: inherit
