name: report-pr

on:
  workflow_run:
    workflows: [validate-schema-pr, pr-check, security, codeql]
    types: [completed]

permissions:
  contents: read

jobs:
  report:
    uses: guilhermelinosp/templates/.github/workflows/pr-report.yml@9aa4a279f308556891c0e24ae61d26c33e36ed3e # templates PR #152
    with:
      app-client-id: ${{ vars.HELLNET_ACTIONS_CLIENT_ID }}
    secrets: inherit
