name: report-pr

on:
  workflow_run:
    workflows: [validate-schema-pr, pr-check, security, codeql]
    types: [completed]

permissions:
  contents: read

jobs:
  report:
    uses: guilhermelinosp/templates/.github/workflows/pr-report.yml@9c844d1f24ca93f397e23834af1277680ed36ca6
    with:
      app-client-id: ${{ vars.HELLNET_ACTIONS_CLIENT_ID }}
    secrets: inherit
