name: report-pr

on:
  workflow_run:
    workflows: [validate-schema-pr, pr-check, security, codeql]
    types: [completed]

permissions:
  contents: read

jobs:
  report:
    uses: guilhermelinosp/templates/.github/workflows/pr-report.yml@41fa69bdb033100b4386fd993d9cf3aff0be1c4f # templates PR #152
    with:
      app-client-id: ${{ vars.HELLNET_ACTIONS_CLIENT_ID }}
    secrets: inherit
